//CUSTOMIZER 
export const ADD_COSTOMIZER ="ADD_COSTOMIZER";
export const ADD_LAYOUT = "ADD_LAYOUT";
export const ADD_SIDEBAR_TYPES = "ADD_SIDEBAR_TYPES";
export const ADD_SIDEBAR_SETTINGS ="ADD_SIDEBAR_SETTINGS";
export const ADD_COLOR = "ADD_COLOR";
export const ADD_MIXlAYOUT = "ADD_MIXlAYOUT";

//PERMISOS
export const INIT_PERMISO = "INIT_PERMISO";
export const ADD_PERMISO = "ADD_PERMISO";
export const ADD_PERMISOS = "ADD_PERMISOS";
export const CLEAR_PERMISOS = "CLEAR_PERMISOS";

//CARGOS
export const CARGO_CHANGE_NAME = "CARGO_CHANGE_NAME";
export const CARGOS_CARGO_PARENT = "CARGOS_CARGO_PARENT";
export const CARGOS_PERMISOS = "CARGOS_PERMISOS";
export const CARGOS_ADD_FUNCIONES = "CARGOS_ADD_FUNCIONES";
export const CARGOS_DEL_FUNCIONES = "CARGOS_DEL_FUNCIONES";
export const CARGOS_INIT = "CARGOS_INIT";
export const CARGOS_STATUS = "CARGOS_STATUS";

//COLABORADORES
export const COLABORADOR_NAME = "COLABORADOR_NAME";
export const COLABORADOR_EMAIL = "COLABORADOR_EMAIL";
export const COLABORADOR_CEDULA = "COLABORADOR_CEDULA";
export const COLABORADOR_DIRECCION = "COLABORADOR_DIRECCION";
export const COLABORADOR_CARGO = "COLABORADOR_CARGO";
export const COLABORADOR_PERMISOS = "COLABORADOR_PERMISOS";
export const COLABORADOR_INIT = "COLABORADOR_INIT";
export const COLABORADOR_STATUS = "COLABORADOR_STATUS";
